// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: producto_venta.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoriaProducto int32

const (
	CategoriaProducto_UNKNOWN     CategoriaProducto = 0
	CategoriaProducto_Electronica CategoriaProducto = 1
	CategoriaProducto_Ropa        CategoriaProducto = 2
	CategoriaProducto_Hogar       CategoriaProducto = 3
	CategoriaProducto_Belleza     CategoriaProducto = 4
)

// Enum value maps for CategoriaProducto.
var (
	CategoriaProducto_name = map[int32]string{
		0: "UNKNOWN",
		1: "Electronica",
		2: "Ropa",
		3: "Hogar",
		4: "Belleza",
	}
	CategoriaProducto_value = map[string]int32{
		"UNKNOWN":     0,
		"Electronica": 1,
		"Ropa":        2,
		"Hogar":       3,
		"Belleza":     4,
	}
)

func (x CategoriaProducto) Enum() *CategoriaProducto {
	p := new(CategoriaProducto)
	*p = x
	return p
}

func (x CategoriaProducto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CategoriaProducto) Descriptor() protoreflect.EnumDescriptor {
	return file_producto_venta_proto_enumTypes[0].Descriptor()
}

func (CategoriaProducto) Type() protoreflect.EnumType {
	return &file_producto_venta_proto_enumTypes[0]
}

func (x CategoriaProducto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CategoriaProducto.Descriptor instead.
func (CategoriaProducto) EnumDescriptor() ([]byte, []int) {
	return file_producto_venta_proto_rawDescGZIP(), []int{0}
}

type ProductSaleRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Categoria       CategoriaProducto      `protobuf:"varint,1,opt,name=categoria,proto3,enum=blackfriday.CategoriaProducto" json:"categoria,omitempty"`
	ProductoId      string                 `protobuf:"bytes,2,opt,name=producto_id,json=productoId,proto3" json:"producto_id,omitempty"`
	Precio          float64                `protobuf:"fixed64,3,opt,name=precio,proto3" json:"precio,omitempty"`
	CantidadVendida int32                  `protobuf:"varint,4,opt,name=cantidad_vendida,json=cantidadVendida,proto3" json:"cantidad_vendida,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProductSaleRequest) Reset() {
	*x = ProductSaleRequest{}
	mi := &file_producto_venta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductSaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSaleRequest) ProtoMessage() {}

func (x *ProductSaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_producto_venta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSaleRequest.ProtoReflect.Descriptor instead.
func (*ProductSaleRequest) Descriptor() ([]byte, []int) {
	return file_producto_venta_proto_rawDescGZIP(), []int{0}
}

func (x *ProductSaleRequest) GetCategoria() CategoriaProducto {
	if x != nil {
		return x.Categoria
	}
	return CategoriaProducto_UNKNOWN
}

func (x *ProductSaleRequest) GetProductoId() string {
	if x != nil {
		return x.ProductoId
	}
	return ""
}

func (x *ProductSaleRequest) GetPrecio() float64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *ProductSaleRequest) GetCantidadVendida() int32 {
	if x != nil {
		return x.CantidadVendida
	}
	return 0
}

type ProductSaleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estado        string                 `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
	Exito         bool                   `protobuf:"varint,2,opt,name=exito,proto3" json:"exito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductSaleResponse) Reset() {
	*x = ProductSaleResponse{}
	mi := &file_producto_venta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductSaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSaleResponse) ProtoMessage() {}

func (x *ProductSaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_producto_venta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSaleResponse.ProtoReflect.Descriptor instead.
func (*ProductSaleResponse) Descriptor() ([]byte, []int) {
	return file_producto_venta_proto_rawDescGZIP(), []int{1}
}

func (x *ProductSaleResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *ProductSaleResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

var File_producto_venta_proto protoreflect.FileDescriptor

const file_producto_venta_proto_rawDesc = "" +
	"\n" +
	"\x14producto_venta.proto\x12\vblackfriday\"\xb6\x01\n" +
	"\x12ProductSaleRequest\x12<\n" +
	"\tcategoria\x18\x01 \x01(\x0e2\x1e.blackfriday.CategoriaProductoR\tcategoria\x12\x1f\n" +
	"\vproducto_id\x18\x02 \x01(\tR\n" +
	"productoId\x12\x16\n" +
	"\x06precio\x18\x03 \x01(\x01R\x06precio\x12)\n" +
	"\x10cantidad_vendida\x18\x04 \x01(\x05R\x0fcantidadVendida\"C\n" +
	"\x13ProductSaleResponse\x12\x16\n" +
	"\x06estado\x18\x01 \x01(\tR\x06estado\x12\x14\n" +
	"\x05exito\x18\x02 \x01(\bR\x05exito*S\n" +
	"\x11CategoriaProducto\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0f\n" +
	"\vElectronica\x10\x01\x12\b\n" +
	"\x04Ropa\x10\x02\x12\t\n" +
	"\x05Hogar\x10\x03\x12\v\n" +
	"\aBelleza\x10\x042h\n" +
	"\x12ProductSaleService\x12R\n" +
	"\rProcesarVenta\x12\x1f.blackfriday.ProductSaleRequest\x1a .blackfriday.ProductSaleResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_producto_venta_proto_rawDescOnce sync.Once
	file_producto_venta_proto_rawDescData []byte
)

func file_producto_venta_proto_rawDescGZIP() []byte {
	file_producto_venta_proto_rawDescOnce.Do(func() {
		file_producto_venta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_producto_venta_proto_rawDesc), len(file_producto_venta_proto_rawDesc)))
	})
	return file_producto_venta_proto_rawDescData
}

var file_producto_venta_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_producto_venta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_producto_venta_proto_goTypes = []any{
	(CategoriaProducto)(0),      // 0: blackfriday.CategoriaProducto
	(*ProductSaleRequest)(nil),  // 1: blackfriday.ProductSaleRequest
	(*ProductSaleResponse)(nil), // 2: blackfriday.ProductSaleResponse
}
var file_producto_venta_proto_depIdxs = []int32{
	0, // 0: blackfriday.ProductSaleRequest.categoria:type_name -> blackfriday.CategoriaProducto
	1, // 1: blackfriday.ProductSaleService.ProcesarVenta:input_type -> blackfriday.ProductSaleRequest
	2, // 2: blackfriday.ProductSaleService.ProcesarVenta:output_type -> blackfriday.ProductSaleResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_producto_venta_proto_init() }
func file_producto_venta_proto_init() {
	if File_producto_venta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_producto_venta_proto_rawDesc), len(file_producto_venta_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_producto_venta_proto_goTypes,
		DependencyIndexes: file_producto_venta_proto_depIdxs,
		EnumInfos:         file_producto_venta_proto_enumTypes,
		MessageInfos:      file_producto_venta_proto_msgTypes,
	}.Build()
	File_producto_venta_proto = out.File
	file_producto_venta_proto_goTypes = nil
	file_producto_venta_proto_depIdxs = nil
}
