apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: valkey-vm
  namespace: black-friday
  labels:
    app: valkey
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        app: valkey
    spec:
      domain:
        cpu:
          cores: 1
          model: host-model # Intenta usar las instrucciones modernas de tu m7i
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 4Gi # <--- ESTO ES CLAVE: 4GB para que vuele
            cpu: 1000m
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: fedora
              password: blackfridaypass
              chpasswd: { expire: False }
              ssh_pwauth: True
              # NOTA: No instalamos paquetes aqui para evitar el timeout
---
apiVersion: v1
kind: Service
metadata:
  name: valkey-service
  namespace: black-friday
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: valkey